### PR TITLE
Added a .NET Core TagHelper implimentation

### PR DESCRIPTION
**Pull request by RemarkLima**
I've added a TagHelper implementation, based upon your original code.

It's working well in my views - the only option would be to change the tag to an `` so it's the correct starting tag. However the `<gravatar />` tag is clear.

### CODE REVIEW

**Comment by AndrewFreemantle** [comment]
Nice, thanks @RemarkLima, please allow me some time to review  😃

**Comment by AndrewFreemantle** [comment]
Thanks @RemarkLima, I've read the current documentation for TagHelpers and while they do look to be the preferred way to create or extend HTML elements in .Net Core MVC, with just a little tweaking of namespaces there's now a HtmlHelper version for .Net Core.

This repository is a HtmlHelper implementation of the Gravatar specification, and on reflection I think it'd be better to have a separate TagHelper repository as it's a slightly different approach. Perhaps you could be the owner of that implementation and create your own repository?  :wink:

Thank you for your contribution  :smiley:

(Closed by commit 7036372a493052438854c639356d687b2ecb3058)

**Comment by RemarkLima** [comment]
Excellent, and good call on the TagHelper - as you say philosophically different, so I'll setup a new repo just for that!

**Comment by AndrewFreemantle** [comment]
Great  :smiley:

Once your repo is up, please comment here and I'll put a link to it in the readme in case someone's after a TagHelper version  :wink:

**Comment by RemarkLima** [comment]
Thanks @AndrewFreemantle - Here it is https://github.com/ia2o/Gravatar-TagHelper

**Pull request closed without merging**
